### ISSUE TITLE
Bangs leave trailing space

### ISSUE THREAD

**Issue by cvincent** [jgdavey/vim-blockle#8] opened 2014-05-07 22:13 UTC
With the following:

```
asdf.each do |a|
  a.stuff!
end
```

Converts to this ("•" denotes the extra space):

```
asdf.each { |a| a.stuff!• }
```

And then back to this (notice the "•"):

```
asdf.each do |a|
  a.stuff!•
end
```

**Comment by jgdavey** [comment] 2016-08-29 23:41
I can reproduce this, but haven't gotten around to looking into fixing it.

**Comment by jgdavey** [comment] 2017-11-18 19:19
Closing this since I'm archiving the project.

**Closed by jgdavey** 2017-11-18 19:19 UTC
